// <auto-generated />
using CityInfo_1.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo_1.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20230523092552_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("CityInfo_1.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Nesibe Konya",
                            Name = "Konya"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fırat Urfa",
                            Name = "Urfa"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Selim Cankiri",
                            Name = "Cankiri"
                        });
                });

            modelBuilder.Entity("CityInfo_1.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Meram",
                            Name = "K1"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Karatay",
                            Name = "K2"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Haliliye",
                            Name = "U1"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Karakopru",
                            Name = "U2"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "BayramOren",
                            Name = "C1"
                        });
                });

            modelBuilder.Entity("CityInfo_1.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo_1.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo_1.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
